### ISSUE TITLE
gắn tag vào post

### ISSUE THREAD

**Issue by ntlzz93** [ntlzz93/BanhKeoTrangAn#10]

**Comment by BruceleeThanh** [comment]
em làm ok rồi, gắn tag vào post (với điều kiện tag enable) nhưng mới hoàn thành chức năng add thôi.
còn edit nữa thì để ngày mai nhé.
Mai xong tag e sẽ làm luôn gắn category.

**Comment by ntlzz93** [comment]
đây là module post à?
