### ISSUE TITLE
prouduct detail 

### ISSUE THREAD

**Issue by ntlzz93** [ntlzz93/BanhKeoTrangAn#13]
issue: phải có ít nhất 1 bản ghi mới hoạt động đúng 

version 14bfb1c

**Comment by BruceleeThanh** [comment]
lỗi khi **truyền tên product** này bác ơi
![bug](https://cloud.githubusercontent.com/assets/7951167/12827390/16cb9b7c-cbb2-11e5-8c4b-fdf1639cfb4b.PNG)

**Comment by BruceleeThanh** [comment]
KindOfProduct **chưa view đc** đa cấp. **em sẽ xử lý** cái này sau nhé
![bug1](https://cloud.githubusercontent.com/assets/7951167/12827486/8d810b94-cbb2-11e5-9aaa-0e9442506ae4.PNG)

**Comment by BruceleeThanh** [comment]
và còn 1 lưu ý nữa là các cái tags, kindofproduct or category **ko** cần loại ra những thằng status = disable. tức là lúc add post hoặc product **vẫn chấp nhận** gắn tags, KOP, category có status = disable. và mình chỉ dùng đến trạng thái khi **view** lên trang **giới thiệu**.

**Comment by ntlzz93** [comment]
cái view đa cấp là issue #15 .
