### ISSUE TITLE
Post List

### ISSUE THREAD

**Issue by ntlzz93** [ntlzz93/BanhKeoTrangAn#9]
Thêm tính năng
Lúc chọn upload ảnh sẽ có 2 trường hợp
1 - là upload ảnh mới từ pc
2 -  là upload ảnh đã có trong db ( hiện ra popup chọn ảnh đã upload những lần trước )

**Comment by BruceleeThanh** [comment]
cái này vẫn chưa giải quyết đc đúng ko nhỉ ???

**Comment by ntlzz93** [comment]
cái này là cái nâng cao thôi . Để sau cũng được. nhãn enhancement là nâng cao mà, tạm thời cứ thế đã
